### ISSUE TITLE
Doesn't handle JUNK chunk

### ISSUE THREAD

**Issue by pschuegr** [TooTallNate/node-wav#13]
Wav file seems to be fine.  Is this chunk type not supported?

```
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: bad "fmt id": expected "fmt ", got "JUNK"
    at Reader._onSubchunk1ID (/Users/pschuegr/dev/mp3copy/node_modules/wav/lib/reader.js:106:24)
    at process (/Users/pschuegr/dev/mp3copy/node_modules/wav/node_modules/stream-parser/index.js:270:20)
    at /Users/pschuegr/dev/mp3copy/node_modules/wav/node_modules/stream-parser/index.js:204:14
    at /Users/pschuegr/dev/mp3copy/node_modules/wav/node_modules/stream-parser/index.js:294:16
    at Reader.transform [as _transform] (/Users/pschuegr/dev/mp3copy/node_modules/wav/node_modules/stream-parser/index.js:176:3)
    at Reader.Transform._read (/Users/pschuegr/dev/mp3copy/node_modules/wav/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at Reader.Transform._write (/Users/pschuegr/dev/mp3copy/node_modules/wav/node_modules/readable-stream/lib/_stream_transform.js:172:12)
    at doWrite (/Users/pschuegr/dev/mp3copy/node_modules/wav/node_modules/readable-stream/lib/_stream_writable.js:237:10)
    at writeOrBuffer (/Users/pschuegr/dev/mp3copy/node_modules/wav/node_modules/readable-stream/lib/_stream_writable.js:227:5)
    at Reader.Writable.write (/Users/pschuegr/dev/mp3copy/node_modules/wav/node_modules/readable-stream/lib/_stream_writable.js:194:11)
```

**Comment by franko-h** [comment]
I added support for this: #16

**Comment by tuxpoldo** [comment]
See https://github.com/YeaSoft/node-wav and https://www.npmjs.com/package/@yeasoft/wav
