### ISSUE TITLE
Throws error upon getting a "JUNK" chunk

### ISSUE THREAD

**Issue by AnoyingShulkerMC** [TooTallNate/node-wav#35]
Sample file: https://fastupload.io/f0a5afb903f73cc9
```
/Users/jerome/Documents/bms2osu/node_modules/wav/lib/reader.js:105
    this.emit('error', new Error(f('bad "fmt id": expected "fmt ", got %j', subchunk1ID)));
                       ^
Error: bad "fmt id": expected "fmt ", got "JUNK"
    at Reader._onSubchunk1ID (/Users/jerome/Documents/bms2osu/node_modules/wav/lib/reader.js:105:24)
    at process (/Users/jerome/Documents/bms2osu/node_modules/stream-parser/index.js:270:20)
    at /Users/jerome/Documents/bms2osu/node_modules/stream-parser/index.js:198:14
    at /Users/jerome/Documents/bms2osu/node_modules/stream-parser/index.js:294:16
    at Reader.transform [as _transform] (/Users/jerome/Documents/bms2osu/node_modules/stream-parser/index.js:176:3)
    at Transform._read (/Users/jerome/Documents/bms2osu/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at Transform._write (/Users/jerome/Documents/bms2osu/node_modules/readable-stream/lib/_stream_transform.js:172:12)
    at doWrite (/Users/jerome/Documents/bms2osu/node_modules/readable-stream/lib/_stream_writable.js:279:12)
    at writeOrBuffer (/Users/jerome/Documents/bms2osu/node_modules/readable-stream/lib/_stream_writable.js:266:5)
    at Writable.write (/Users/jerome/Documents/bms2osu/node_modules/readable-stream/lib/_stream_writable.js:211:11)
```

**Comment by yujonglee** [comment]
#16

**Comment by tuxpoldo** [comment]
See https://github.com/YeaSoft/node-wav and https://www.npmjs.com/package/@yeasoft/wav
